language: node_js
node_js:
- '11'
jobs:
  include:
  - stage: Deploy
    if: branch = master
    cache: npm
    script:
    - npm i
    - npm run build
    deploy:
      provider: pages
      local_dir: dist/
      target-branch: gh-pages
      name: Travis Deployment Bot
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      fqdn: startupmap.ratemystop.com
      on:
        branch: master
notifications:
  email: false
env:
  global:
    secure: WvmOQ1CLn5FCHGydzBVZia6Sx9njj6Ge0/Jd8PWPuZ/xiY7itlPwAJ88Zyf2Y6BrXYUk6hlwahsHkjy2/b85JZZaUAuUQ2lTAdep6em8fBnTFov1/8/KTqxvDxz3pszLXSSpeKcedfYI6SwSZ2Xk4hAsH/rck3/pcsiJUxSjTuHYPQeVHnH2n2SgpIueMI/hBfnZld0MO9fDmLeRQi7kqkenJNOwzRlqfYw0lg2OGolYP8jV6u0CDxIMScRi3q4T9TUlcTm53xslZrd1U/wHncbXvAli0wuuCzBC0TrzKSaqNCJCaRplh4GRrmgPYrR1kpZ3EC0XffKl5lcOwpzvMvYhTnBiwXen+2Qru2uAXE0FTz7bH5fll3jWhmTf3hBgZZ37iDndoOAddQKMUUCnlQc7UF2LjOv1J5HXfboaGIHq5xGdr8cLdatBvWD5cI93ZgXCRHAiFlasuIMkJOdXbqv7+1+Jv95NeswVuG1yRalYBtiv1gzXfMPsZjPLUWLONt3LK1Q1TrhKVRwgajVroqziruTY8rZlq0IPrlNDKsefRlKSeMTCfYXV89wKM0/wKG86e12lcC/lJtPiV4VI1ICprobKI91+f+dQ2UpaWJyzAlOTFgV/pGHDgRxd8MKZs6BUbzW6KJu8Kdv79ri8ink2n2X0X+D3zycgjJnUo0Y=
